name: CI & CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up Python & UV
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install UV
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      # 3) Run your unit tests
      - name: Run tests
        run: PYTHONPATH=. uv run pytest --maxfail=1 --disable-warnings -q

      # 4) Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 5) Set up gcloud CLI
      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 6) Configure gcloud auth
      - name: Configure gcloud & docker
        run: |
          gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"
          gcloud auth configure-docker --quiet

      # 7) Build and push Docker image to GCR
      - name: Build & push Docker image to GCR
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/phishing-ml:end2end .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/phishing-ml:end2end

      # 8) Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy phishing-ml \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/phishing-ml:end2end \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
