# .github/workflows/ci.yml
name: CI & CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up Python & install uv
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install UV
        run: pip install uv

      # 3) Install project dependencies
      - name: Sync dependencies
        run: uv sync

      # 4) Download NLTK stopwords (required for prediction)
      - name: Download NLTK stopwords
        run: uv run python -m nltk.downloader stopwords

      # 5) Run unit tests
      - name: Run tests
        run: PYTHONPATH=. uv run pytest --maxfail=1 --disable-warnings -q

      # 6) Authenticate to Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 7) Set up gcloud CLI
      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 8) Configure Docker for GCR
      - name: Configure gcloud auth & Docker
        run: |
          gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"
          gcloud auth configure-docker --quiet

      # 9) Build & push Docker image to Google Container Registry
      - name: Build & push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/phishing-ml:end2end .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/phishing-ml:end2end

      # 10) Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy phishing-ml \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/phishing-ml:end2end \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
